### ISSUE TITLE
No task to suspend in defer

### ISSUE THREAD

**Issue by kostya** [celluloid/celluloid#232]
0.13.0 works.

``` ruby
require 'celluloid'

class A
  include Celluloid

  def bla(&block)
    defer do
      yield 1
    end
  end
end

a = A.new
a.bla{|c| p c }
```

```
E, [2013-05-02T04:30:02.423694 #6142] ERROR -- : A crashed!
RuntimeError: No task to suspend
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/proxies/block_proxy.rb:21:in `block in to_proc'
    1.rb:9:in `block in bla'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/calls.rb:25:in `call'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/calls.rb:25:in `public_send'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/calls.rb:25:in `dispatch'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/calls.rb:67:in `dispatch'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/future.rb:21:in `block in initialize'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/internal_pool.rb:59:in `call'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/internal_pool.rb:59:in `block in create'
    (celluloid):0:in `remote procedure call'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/future.rb:114:in `value'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/future.rb:78:in `value'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid.rb:477:in `defer'
    1.rb:8:in `bla'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/calls.rb:25:in `public_send'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/calls.rb:25:in `dispatch'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/calls.rb:67:in `dispatch'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/actor.rb:328:in `block in handle_message'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/tasks.rb:42:in `block in initialize'
    /home/kostya/.rvm/gems/ruby-2.0.0-p0/gems/celluloid-0.14.0.pre/lib/celluloid/tasks/task_fiber.rb:9:in `block in create'
```

**Comment by digitalextremist** [comment]
This has introduced instability I'm afraid.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
