### ISSUE TITLE
Calling instance_eval from initialize crashes actor.

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid#421]
For more specific details, see https://github.com/celluloid/celluloid-io/issues/108

```
E, [2014-05-21T10:56:15.627263 #75097] ERROR -- : Actor crashed!
NoMethodError: undefined method `<<' for nil:NilClass
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/proxies/block_proxy.rb:16:in `block in to_proc'
    /Users/samuel/Documents/Programming/Internet/rubydns/lib/rubydns/server.rb:277:in `instance_eval'
    /Users/samuel/Documents/Programming/Internet/rubydns/lib/rubydns/server.rb:277:in `initialize'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `public_send'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:26:in `dispatch'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/calls.rb:63:in `dispatch'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:60:in `block in invoke'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Users/samuel/.rvm/gems/ruby-2.1.2/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by tilo** [comment]
@ioquatix does this fix work reliably?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
