### ISSUE TITLE
Sidekiq dying with 0.16.0pre

### ISSUE THREAD

**Issue by cibernox** [celluloid/celluloid#438]
I suffered some problems today with sidekiq today after updating celluloid. I have no idea of the cause, but jobs started to fail and eventually sidekiq falls apart.

This is the stack trace:
```
2014-05-30T19:19:00Z 27641 TID-2lmct4 WARN: Sidekiq died due to the following error, cannot recover, process exiting
2014-05-30T19:19:00Z 27641 TID-2lmct4 WARN: wtf
2014-05-30T19:19:00Z 27641 TID-2lmct4 WARN: /var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:195:in `
block (2 levels) in linking_request'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:177:in `loop'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:177:in `block in linking_request'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:104:in `exclusive'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid.rb:414:in `exclusive'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:172:in `linking_request'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:56:in `monitor'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:67:in `link'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid.rb:179:in `new_link'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/sidekiq-3.0.0/lib/sidekiq/manager.rb:100:in `block in processor_died'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/sidekiq-3.0.0/lib/sidekiq/util.rb:15:in `watchdog'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/sidekiq-3.0.0/lib/sidekiq/manager.rb:94:in `processor_died'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:15:in `block in call'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/cell.rb:71:in `block in task'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/actor.rb:362:in `block in task'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks.rb:55:in `block in initialize'
/var/www/golden_manager/shared/bundle/ruby/2.1.0/gems/celluloid-0.16.0.pre/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

I am reporting this here because the stack trace is very similar to this one here https://github.com/mperham/sidekiq/issues/1161 and aparently was a bug solved in 0.15.1.

Let me know if I can help here with something tracing this.

**Comment by digitalextremist** [comment]
This has been dormant for a while. Is it still an issue?

**Comment by digitalextremist** [comment]
Please reopen this if it is still relevant.
