### ISSUE TITLE
Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 

### ISSUE THREAD

**Issue by rupweb** [celluloid/celluloid#442]
We are using PubNub "Publisher" to publish data for several months without issue, when suddenly we have been hit with the following error. Can you comment please?
```
•	Jun 20 09:52:01  engine.log: Publisher crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:327:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: RedisPublisher crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:327:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: Supervisor crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: Supervisor#finalize crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:382:in `run_finalizer' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:372:in `shutdown' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:365:in `handle_crash' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:209:in `rescue in run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:193:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: SurfFeedIO crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: SurfFeedIO#finalize crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:382:in `run_finalizer' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:372:in `shutdown' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:365:in `handle_crash' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:209:in `rescue in run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:193:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: TriggerWorker crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: Monitor crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: Runner crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: PushRate crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: Parser crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: CrossWorker crashed! 
•	Jun 20 09:52:01  engine.log: Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:51:in `rescue in resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/tasks/task_fiber.rb:46:in `resume' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:401:in `task' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:340:in `handle_system_event' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:325:in `handle_message' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:196:in `run' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/actor.rb:184:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/thread_handle.rb:17:in `block in initialize' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `call' 
•	Jun 20 09:52:01  engine.log: /home/.rvm/gems/ruby-2.1.1/gems/celluloid-0.12.4/lib/celluloid/internal_pool.rb:48:in `block in create' 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier cannot resume a dead task (can't alloc machine stack to fiber: Operation not permitted) 
•	Jun 20 09:52:01  engine.log: 2014-06-20 07:52:01 +0000 Notifier terminating actor 
```

**Comment by digitalextremist** [comment]
@rupweb if this was in fact Celluloid related, please let us know.
