### ISSUE TITLE
Actor crashed and cleanup crashed when running a Celluloid class via cron

### ISSUE THREAD

**Issue by rahilsondhi** [celluloid/celluloid#489]
I have a class that includes `Celluloid`. When I run the class in a rails console, it works. But when I ask crontab to run it, I get this error in the log:

```
Actor crashed!
RuntimeError:
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `resume'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:353:in `task'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:67:in `task'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:59:in `invoke'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/cell.rb:34:in `block in initialize'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19:in `handle_message'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:280:in `handle_message'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:154:in `block in run'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/timers-4.0.1/lib/timers/group.rb:52:in `wait'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
CLEANUP CRASHED!
Celluloid::MailboxDead: mailbox already shutdown
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/mailbox.rb:85:in `shutdown'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:338:in `cleanup'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
        /var/rails/turtle/shared/bundle/ruby/1.9.1/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

I'd really appreciate any ideas :confused: , thanks!

**Comment by rahilsondhi** [comment]
I think it's because my class is doing a bunch of things asyncronously, so when cron calls the class, everything appears to be finished in a second, and the process is killed, which kills the processes running in the background.

My next question is then, how can I persist the process so that it waits for the actors to complete? I don't necessarily need asyncronicity, but I do want the concurrency that Celluloid offers.

**Comment by k-solutions** [comment]
Some code may give some sense to what you ask

**Comment by digitalextremist** [comment]
@rahilsondhi we need a reproduction to be able to help here.

**Comment by rahilsondhi** [comment]
Sorry, a lot of time has passed and this question is no longer relevant for me.
