### ISSUE TITLE
RuntimeError: Cannot terminate an exclusive task

### ISSUE THREAD

**Issue by fedenusy** [celluloid/celluloid#494]
Every once in a while, I see this error in 3 different places, always in quick succession:

```
CLEANUP CRASHED!
RuntimeError: Cannot terminate an exclusive task
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:116:in `terminate'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

```
SystemStackError: stack level too deep
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb" line 25
Celluloid::FiberStackError: stack level too deep (please see https://github.com/celluloid/celluloid/wiki/Fiber-stack-errors)
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb" line 27 in rescue in deliver
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb" line 25 in deliver
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb" line 96 in resume
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 359 in task
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb" line 67 in task
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb" line 59 in invoke
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb" line 34 in block in initialize
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb" line 38 in call
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb" line 38 in call
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb" line 19 in handle_message
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 280 in handle_message
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 154 in block in run
File "/var/lib/gems/2.1.0/gems/timers-4.0.1/lib/timers/group.rb" line 52 in wait
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 150 in run
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 130 in block in start
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb" line 13 in block in initialize
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb" line 32 in block in get_thread
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb" line 130 in call
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb" line 130 in block in create
RuntimeError: Cannot terminate an exclusive task
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb" line 116 in terminate
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb" line 34 in terminate
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 345 in each
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 345 in cleanup
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 329 in shutdown
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 321 in handle_crash
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 166 in rescue in run
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 148 in run
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb" line 130 in block in start
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb" line 13 in block in initialize
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb" line 32 in block in get_thread
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb" line 130 in call
File "/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb" line 130 in block in create
```

```
Actor crashed!
Celluloid::FiberStackError: stack level too deep (please see https://github.com/celluloid/celluloid/wiki/Fiber-stack-errors)
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:27:in `rescue in deliver'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:359:in `task'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:67:in `task'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:59:in `invoke'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:34:in `block in initialize'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19:in `handle_message'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:280:in `handle_message'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:154:in `block in run'
	/var/lib/gems/2.1.0/gems/timers-4.0.1/lib/timers/group.rb:52:in `wait'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
	/var/lib/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

Running `RubyVM::DEFAULT_PARAMS` in IRB returns the following:

```
=> {:thread_vm_stack_size=>1048576, :thread_machine_stack_size=>1048576, :fiber_vm_stack_size=>131072, :fiber_machine_stack_size=>524288}
```

...so I'm pretty sure this isn't your typical `FiberStackError`. Any idea what may be going on?

I should add that I grep'd my codebase for any mentions of `terminate`. All `terminate` calls to exclusive actors are made asynchronously.

**Comment by fedenusy** [comment]
I should add that I grep'd my codebase for all mentions of `terminate`. *All* `terminate` calls to exclusive actors are made asynchronously.

**Comment by digitalextremist** [comment]
@fedenusy do you have a repro I can use to help fix this?

**Comment by fedenusy** [comment]
@digitalextremist as far as I can tell the error is non-deterministic, but I'm happy to spend some time trying to repro. Any idea what celluloid features I should focus on?

I see mentions of "timers" in the stack traces, and there's also mentions of "terminat[ing] an exclusive task". Do you think it make sense for me to focus on exclusive actors in my app that use timers? Or is that not the right place to start?

**Comment by digitalextremist** [comment]
Hmm. Time invested in a repro would be much appreciated. I would start as close to how you originally stumbled upon the error as possible and see how it goes. May the f0rc3 be with you.

**Comment by fedenusy** [comment]
Any chance it would be possible to modify the errors above so they include the actor class that triggered the error? For example, "Actor crashed!" would be way more helpful if it said "MyActorClass actor crashed!"

As it stands, I have to look through my entire app to try and repro, which feels a bit daunting.

Either way I'll try repro early next week.

**Comment by digitalextremist** [comment]
Have you tried `Task::Threaded` and/or using the `0.17.0-prerelease` branch?

**Comment by fedenusy** [comment]
Tried finding repro a couple days ago but no luck. I'm guessing some change in my app inadvertently "fixed" this, since I'm not seeing it anymore. I'll upgrade to 0.17 and let you know if it happens again.

I should also mention I saw a similar error about a week ago. This one was much more frequent, and thus easier to find. After some digging it turned out to be a bug in my app that resulted in infinite recursion. But since it looked like the errors above, there was absolutely no hint of where to start debugging.

Would be really nice if celluloid mentioned the actor class / method name / line number that triggered a `FiberStackError` (maybe this is already in on 0.17)?

**Comment by digitalextremist** [comment]
Be advised @fedenusy, `0.17.0` might singe your eyebrows off. `Task::Threaded` has backtraces, but if you want to post an issue requesting this feature just in case, go ahead. I don't see it happening until `0.18.0` though, but you can file it. For now I'm going to close this unless you can reproduce it solidly.

**Comment by fedenusy** [comment]
Sounds good, thanks for all the help.
