### ISSUE TITLE
Why might Actors fail to link?

### ISSUE THREAD

**Issue by DaveCollinsJr** [celluloid/celluloid#601]
Hello,
  Working with sidekiq-pro on AWS EB instances.  Basically everything is running fine, but sometimes one or more of our instances will fail to run sidekiq for more than 30 seconds.  Looking into the logs on that machine, and we see this in the log:

```
2015-04-21T18:13:14.237Z 9749 TID-bwxvs INFO: Booting Sidekiq 3.3.2 with redis options {:url=>"redis://sentrylink-quality-2.saki9c.0001.use1.cache.amazonaws.com:6379", :namespace=>"mps-quality"}
2015-04-21T18:13:19.684Z 9749 TID-bwxvs INFO: Running in ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
2015-04-21T18:13:19.685Z 9749 TID-bwxvs INFO: Sidekiq Pro 1.9.2, commercially licensed.  Thanks for your support!
2015-04-21T18:13:32.579Z 9749 TID-1ns8b4 WARN: Sidekiq died due to the following error, cannot recover, process exiting
2015-04-21T18:13:32.715Z 9749 TID-1ns8b4 WARN: linking timeout of 5 seconds exceeded
2015-04-21T18:13:32.779Z 9749 TID-1ns8b4 WARN: /var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:206:in `block in linking_request'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:107:in `exclusive'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid.rb:414:in `exclusive'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:177:in `linking_request'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:57:in `monitor'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:68:in `link'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid.rb:366:in `link'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-04-21T18:13:33.781Z 9749 TID-wgzlg INFO: [Sidetiq] Sidetiq::Actor::Clock id: 54526060 shutting down ...
2015-04-21T18:13:33.782Z 9749 TID-wgzlg WARN: {:context=>"Sidetiq::Clock#loop!"}
2015-04-21T18:13:33.782Z 9749 TID-wgzlg WARN: task was terminated
2015-04-21T18:13:33.782Z 9749 TID-wgzlg WARN: /var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/var/app/current/vendor/bundle/ruby/2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
2015-04-21T18:13:33.982Z 9749 TID-otrkf3odk INFO: [Sidetiq] Sidetiq::Actor::Handler id: 70039206351920 shutting down ...
2015-04-21T18:13:34.082Z 9749 TID-cee9g INFO: [Sidetiq] Sidetiq::Actor::Handler id: 19871580 shutting down ...
2015-04-21T18:13:34.082Z 9749 TID-gn0m4 INFO: [Sidetiq] Sidetiq::Actor::Handler id: 23572000 shutting down ...
```

Mike Perham of sidekiq fame indicated he had "literally never seen this error before" and asked that I post it here.

Versions we are running:
  * celluloid (0.16.0)
  * sidekiq (3.3.2)
  * sidekiq-pro (1.9.2)
  * sidetiq (0.6.3)

Would appreciate any guidance or suggestions!

**Comment by digitalextremist** [comment]
This is a problem which is happening more frequently. I will watch this and try to get it into `0.17.0`

**Comment by mperham** [comment]
I believe it might be due to Sidetiq taking a lot of time to initialize.  @DaveCollinsJr is it possible that you have a pretty big Sidetiq job schedule?  Are you using the latest Sidetiq?

**Comment by mperham** [comment]
I'd point you to these two issues, it's very easy to define your job schedules such that ice_cube uses a huge amount of CPU, making startup extremely slow:

https://github.com/tobiassvn/sidetiq/issues/127
https://github.com/tobiassvn/sidetiq/issues/31

**Comment by digitalextremist** [comment]
@mperham can Sidekiq be refactored in a way where very little happens in `initialize` *ever*? I can look at this if you like.

**Comment by mperham** [comment]
I'm referring to sidetiq, not Sidekiq.

**Comment by DaveCollinsJr** [comment]
Thanks for the responses.  To answer some of the posed questions:
1) Not sure what you mean by "pretty big" regarding our job schedule.  We have 21 workers that use a recurrence setting.  *How long is a piece of string?*
2) Yes we are using the current sidetiq 0.6.3

Of our 21 workers using recurrence **two** of them were using the dreaded "minutely" settting.  I am changing those two to use hourly.minute_of_hour as advised in the posts you linked.  None of our workers are millisecond (or even second) time critical - they just need to happen some time around those intervals.

Will see if this helps!
Thanks

**Comment by DaveCollinsJr** [comment]
Just wanted to update this!

After modifying the two workers that used "minutely", this problem has been eliminated!

Really appreciate the help.
