### ISSUE TITLE
Celluloid::DeadTaskError from within Postgres transaction

### ISSUE THREAD

**Issue by stavro** [celluloid/celluloid#613]
Setup:
  * Ruby 2.1.2
  * Celluloid 0.16
  * Pg 0.17.1

I cannot make a synchronous call to another actor from within a pg transaction block.

Minimally complete example:

```ruby
require 'celluloid'
require 'uri'
require 'pg'

class Child
  include Celluloid

  def test
    true
  end
end

class Parent
  include Celluloid

  def initialize
    uri = URI.parse(ENV['PG_URL'])
    @pg = PG.connect(uri.hostname, uri.port, nil, nil, uri.path[1..-1], uri.user, uri.password)
    @child = Child.new_link
  end

  def test
    @pg.transaction do
      @child.test
    end
  end
end

p = Parent.new
p.test =>

E, [2015-05-05T15:15:10.323034 #77954] ERROR -- : Actor crashed!
Celluloid::DeadTaskError: cannot resume a dead task (fiber called across stack rewinding barrier)
  .../gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:29:in `rescue in deliver'
  .../gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
  .../gems/celluloid-0.16.0/lib/cellFiberError: fiber called across stack rewinding barrieruloid/tasks.rb:96:in `resume'
  .../gems/celluloid-0.16.0/lib/celluloid/actor.rb:359:in `task'
  .../gems/celluloid-0.16.0/lib/celluloid/cell.rb:67:in `task'
  .../gems/celluloid-0.16.0/lib/celluloid/cell.rb:59:in `invoke'
  .../gems/celluloid-0.16.0/lib/celluloid/cell.rb:34:in `block in initialize'
  from .../gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:20:in `yield'
  from .../gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:20:in `signal'
  from .../gems/celluloid-0.16.0/lib/celluloid/tasks.rb:85:in `suspend'
  from .../gems/celluloid-0.16.0/lib/celluloid/tasks.rb:24:in `suspend'
  from .../gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
  .../gems/celluloid-0.16.0/lib/celluloid/handlers.rb:38:in `call'
  .../gems/celluloid-0.16.0/lib/celluloid/handlers.rb:19:in `handle_message'
  .../gems/celluloid-0.16.0/lib/celluloid/actor.rb:280:in `handle_message'
  .../gems/celluloid-0.16.0/lib/celluloid.rb:114:in `suspend'
  from .../gems/celluloid-0.16.0/lib/celluloid/calls.rb:88:in `response'
  from .../gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
  from .../gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
  from (irb):567:in `block in test'
  from (irb):566:in `transaction'
  from (irb):566:in `test'
  from .../gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
  from .../gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
  from .../gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
  from .../gems/celluloid-0.16.0/lib/celluloid/actor.rb:154:in `block in run'
  .../gems/timers-4.0.1/lib/timers/group.rb:52:in `wait'
  .../gems/celluloid-0.16.0/lib/celluloid/actor.rb:150:in `run'
  .../gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
  .../gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
  .../gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
  .../gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
  .../gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
```

**Comment by tarcieri** [comment]
Regardless of what's actually happening, this seems like a bad idea to me in general

**Comment by stavro** [comment]
I was attempting to utilize a cursor to iterate through a large query (cursors must be executed from within a transaction) and pass the processing off to another worker.

A periodic synchronous call was issued for backpressure to prevent the queue from being completely overwhelmed.

**Comment by stavro** [comment]
I can fix this on my end now that I know the root cause, but I wanted to share the problem in case the Celluloid gem wants to investigate.

**Comment by digitalextremist** [comment]
Please repost this if you're still having this issue with `0.17.0` ... even though this seems like a legitimate error... nesting Fiber handling.
