### ISSUE TITLE
LoadError: cannot load such file -- win32ole on OSX - celluloid-essentials-0.20.1

### ISSUE THREAD

**Issue by Micka33** [celluloid/celluloid#651]
@digitalextremist Thanks for the hard work !

However I get a new error now.

You asked me which operating system and RVM I am using:
```
rvm 1.26.11
OSX Yosemite
```

Here is the error :
```
namespace should be set in your ruby initializer, is ignored in config file
config.redis = { :url => ..., :namespace => 'namespace_dev' }
D, [2015-07-20T12:17:14.819053 #84626] DEBUG -- : Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
2015-07-20T10:17:15.564Z 84626 TID-ovftx0h60 INFO: [Sidetiq] Sidetiq v0.6.3 - Copyright (c) 2012-2013, Tobias Svensson <tob@tobiassvensson.co.uk>
2015-07-20T10:17:15.564Z 84626 TID-ovftx0h60 INFO: [Sidetiq] Sidetiq is covered by the 3-clause BSD license.
2015-07-20T10:17:15.564Z 84626 TID-ovftx0h60 INFO: [Sidetiq] See LICENSE and http://opensource.org/licenses/BSD-3-Clause for licensing details.
2015-07-20T10:17:15.564Z 84626 TID-ovftx0h60 INFO: [Sidetiq] Sidetiq::Supervisor start
2015-07-20T10:17:15.565Z 84626 TID-ovfu2yi9c INFO: [Sidetiq] Sidetiq::Actor::Clock id: 70170397578020 initialize
2015-07-20T10:17:15.565Z 84626 TID-ovfu2yi9c DEBUG: [Sidetiq] Sidetiq::Clock looping ...
2015-07-20T10:17:15.568Z 84626 TID-ovfu2vc6o ERROR: Actor crashed!
LoadError: cannot load such file -- win32ole
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `require'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `from_win32ole'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:12:in `count_cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:6:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:96:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:22:in `initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
2015-07-20T10:17:15.568Z 84626 TID-ovfu309eo ERROR: Actor crashed!
LoadError: cannot load such file -- win32ole
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `require'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `from_win32ole'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:12:in `count_cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:6:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:96:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:22:in `initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:45:in `value'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/sync.rb:40:in `method_missing'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/cell.rb:20:in `_send_'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:204:in `new_link'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container/instance.rb:34:in `start'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container/instance.rb:29:in `initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container.rb:73:in `new'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container.rb:73:in `add'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/deprecate/supervise.rb:96:in `supervise'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/behavior/pool.rb:29:in `pool'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
2015-07-20T10:17:15.569Z 84626 TID-ovfu2vc6o ERROR: thread crashed
LoadError: cannot load such file -- win32ole
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `require'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `from_win32ole'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:12:in `count_cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:6:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:96:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:22:in `initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:45:in `value'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/sync.rb:40:in `method_missing'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/cell.rb:20:in `_send_'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:204:in `new_link'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container/instance.rb:34:in `start'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container/instance.rb:29:in `initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container.rb:73:in `new'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container.rb:73:in `add'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/deprecate/supervise.rb:96:in `supervise'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/behavior/pool.rb:29:in `pool'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
2015-07-20T10:17:15.570Z 84626 TID-ovfu2yi9c INFO: [Sidetiq] Sidetiq::Actor::Clock id: 70170397578020 shutting down ...
2015-07-20T10:17:15.571Z 84626 TID-ovfu309eo WARN: Terminating task: type=:call, meta={:dangerous_suspend=>true, :method_name=>:initialize}, status=:callwait
	Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
2015-07-20T10:17:15.571Z 84626 TID-ovfu309eo ERROR: thread crashed
LoadError: cannot load such file -- win32ole
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `require'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:43:in `from_win32ole'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celltask was terminateduloid/internals/cpu_counter.rb:12:in `count_cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/cpu_counter.rb:6:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:96:in `cores'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:22:in `initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:35:in `terminate'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:347:in `block in cleanup'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:345:in `each'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:345:in `cleanup'
/Users/mickael/.rv.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/cellum/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:331:in `shutdown'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:323:in `handle_crash'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:171:in `rescue in run'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:150:in `run'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/loid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:45:in `value'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/sync.rb:40:in `method_missing'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/cell.rb:20:in `_send_'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:204:in `new_link'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container/instance.rb:34:in `start'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container/instance.rb:29:in `initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/container.rb:73:in `new'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:132:in `block in start'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-essentials-0.20.1/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor_system.rb:76:in `block in get_thread'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/group/spawner.rb:54:in `call'/lib/celluloid/supervision/container.rb:73:in `add'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/deprecate/supervise.rb:96:in `supervise'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/behavior/pool.rb:29:in `pool'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/Users/mickael/.rvm/rub
/Useries/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
s/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/group/spawner.rb:54:in `block in instantiate'
(celluloid):0:in `remote procedure call'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:45:in `value'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/sync.rb:40:in `method_missing'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid/proxy/cell.rb:20:in `_send_'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-0.17.0/lib/celluloid.rb:193:in `new'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/celluloid-supervision-0.20.0/lib/celluloid/supervision/deprecate/supervise.rb:61:in `run!'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/supervisor.rb:33:in `run!'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq.rb:65:in `<top (required)>'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
/Users/mickael/Documents/folder/projectname/config/application.rb:7:in `<top (required)>'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:236:in `require'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:236:in `boot_system'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.4/lib/sidekiq/cli.rb:50:in `run'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.4/bin/sidekiq:8:in `<top (required)>'
/Users/mickael/.rvm/gems/ruby-2.1.5/bin/sidekiq:23:in `load'
/Users/mickael/.rvm/gems/ruby-2.1.5/bin/sidekiq:23:in `<main>'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bin/ruby_executable_hooks:15:in `<main>'
2015-07-20T10:17:15.573Z 84626 TID-ovftx0h60 DEBUG: Terminating 5 actors...
```

referencing https://github.com/celluloid/celluloid/issues/650 for follow up.

**Comment by digitalextremist** [comment]
@Micka33 we can keep this in the `celluloid-essentials` gem. I've posted a patch there.

**Comment by digitalextremist** [comment]
Ignore previous commit message.
