### ISSUE TITLE
Poolmanager errors with 'private method' error when calling a worker method

### ISSUE THREAD

**Issue by gunnarmarten** [celluloid/celluloid#663]
Hey,
I recently upgraded from celluloid 0.16.0 to 0.16.1 and our logging class isn't working anymore.
I'm using ruby-2.1.5 on OSX 10.8.5.

I stripped it down to this code:
```ruby
require 'celluloid'

class CelluloidLogger
  include Celluloid

  def info
    puts "info"
  end
  def warn
    puts "warn"
  end
  def log
    puts "log"
  end
end
logger = CelluloidLogger.pool
logger.info
logger.warn
logger.log
```

If I execute this code with celluloid 0.16.1 or 0.17 get this error:
```
E, [2015-08-11T13:47:38.929786 #6215] ERROR -- : Actor crashed!
NoMethodError: private method `warn' called for #<Celluloid::PoolManager:0x007fa14b7b1c88>
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/pool_manager.rb:164:in `method_missing'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
D, [2015-08-11T13:47:38.931621 #6215] DEBUG -- : Terminating 9 actors...
D, [2015-08-11T13:47:38.939266 #6215] DEBUG -- : Terminating task: type=:finalizer, meta={:method_name=>:__shutdown__}, status=:receiving
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/pool_manager.rb:164:in `method_missing': private method `warn' called for #<Celluloid::PoolManager:0x007fa14b7b1c88> (NoMethodError)
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
	from /Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from test_celluloid.rb:20:in `<main>'
```

So the behavior worker methods are looked up and called has changed since 0.16.0 and now celluloid wants to call private method from a super class.
If I debug into poolmanager:146 i get `#<UnboundMethod: CelluloidLogger#info>` for my `:info` worker method and 
`#<Method: Celluloid::PoolManager(Kernel)#warn>` for the `:warn` method

Looking at the changes between celluloid 0.16.0 and 0.16.1 it might be related to the changes done in #472, #473, #474

**Comment by digitalextremist** [comment]
Have you tried this with `0.17.1.1` by chance?

I also have noticed problems with `warn` being somewhat impossible to override or rename. Yes, I notice that `Kernel.warn` is called, even if it is overridden. I'll look further into this.

Question: Why is your logger implemented as a pool, rather than as just `async` methods?

**Comment by gunnarmarten** [comment]
I just tried `0.17.1.1`, same issue:

```
E, [2015-08-11T16:48:37.752837 #9145] ERROR -- : Actor crashed!
NoMethodError: private method `warn' called for #<Celluloid::Supervision::Container::Pool:0x007f95b4036460>
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:201:in `method_missing'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/calls.rb:28:in `public_send'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/calls.rb:28:in `dispatch'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/call/sync.rb:16:in `dispatch'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/cell.rb:50:in `block in dispatch'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/cell.rb:76:in `block in task'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/actor.rb:338:in `block in task'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/task.rb:44:in `block in initialize'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/call/sync.rb:45:in `value'
	/Users/gunnar/.rvm/gems/ruby-2.1.5@notification_service/gems/celluloid-0.17.1.1/lib/celluloid/proxy/sync.rb:38:in `method_missing'
	test_celluloid.rb:20:in `<main>'
```

Hmm, i'm not a 100% sure how this developed to use a pool, its some pretty old code. We're using the logger in different projects with sometimes a lot of workers and sometimes just one. So we use sometimes a pool and sometimes none but the call of the logger stays the same `logger.info`. And we wanted to make sure that the logs are written to the log sink in the calling order but correct me if i'm wrong that's probably not an issue when using the `async` methods.

**Comment by digitalextremist** [comment]
You are less likely to get things to happen in calling order with a pool than with async. I personally use async religiously for logging.

Question: Do all the other levels besides `warn` work?

**Comment by gunnarmarten** [comment]
Yeah, all the other levels do work, it's the `warn` that isn't called correctly. If I just use an actor instead of the pool everything works fine.

**Comment by digitalextremist** [comment]
This tells me that the same situation as what I experienced is happening... I was using `extend Forwardable` and delegating that log level... which caused what you're experiencing. It seems something is clobbering redirected references, rather than direct method invocations... since you are working through proxies and not touching the object itself.

**Comment by digitalextremist** [comment]
Interesting factoid, if you trace this, I bet you will find that if you run `method(:warn).source_location` it will show you a `Kernel` reference.

**Comment by digitalextremist** [comment]
Please re-open if this is still an issue for you!
