### ISSUE TITLE
Actor crashes when stopping the Rails 5.0.0.beta1 beta puma server

### ISSUE THREAD

**Issue by dhh** [celluloid/celluloid#697]
If you've engaged the Celluloid server on a Rails 5.0.0.beta1 app (do this by enabling the cable in JS + routes.rb, then call just `App.cable.send("whatever")`, and you quit the development server with CTRL-C, you get a dead actor exception:

```
Started GET "/cable/" [WebSocket] for ::1 at 2015-12-20 08:34:10 +0100
Received unrecognized command in "whatever"
^CExiting
Actor crashed!
Celluloid::DeadActorError: attempted to call a dead actor
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/proxy/sync.rb:25:in `method_missing'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/2.2.0/set.rb:308:in `delete'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/2.2.0/set.rb:308:in `delete'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-pool-0.20.5/lib/celluloid/supervision/container/pool.rb:163:in `__crash_handler__'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/cell.rb:15:in `block in call'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/cell.rb:76:in `block in task'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/actor.rb:339:in `block in task'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/task.rb:44:in `block in initialize'
    /Users/david/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.17.2/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by dhh** [comment]
//cc @tarcieri

**Comment by tarcieri** [comment]
FWIW, I tried to repro this and got as far as this ExecJS error:

```
ExecJS::RuntimeError: SyntaxError: [stdin]:8:17: missing / (unclosed regex)
```

Mind pushing up a repo that has a ready-to-go reproduction of the problem?

**Comment by ioquatix** [comment]
I believe this has been fixed. It was due to some issues with removing a dead actor from a `Set`. I fixed this in c56438658fd376a4cd0897673ddbe04efecfc5e2.  Can you please re-test and confirm this is no longer an issue @dhh

**Comment by digitalextremist** [comment]
How is this looking? Resolved? Need point release?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
