### ISSUE TITLE
Remove default at_exit handler?

### ISSUE THREAD

**Issue by tarcieri** [celluloid/celluloid#698]
Celluloid automatically installs an `at_exit` handler when `celluloid` is required, which just calls `Celluloid.shutdown`. Maybe it shouldn't.

With Rails pulling in Celluloid by default now, this becomes pretty onerous. I think it's contributing to #697.

Celluloid has always straddled the line between library and framework. I think most people end up using it as a library, and for them, the default `at_exit` handler probably isn't helping. Furthermore, the shutdown system has some pretty longstanding problems, and unless it works reliably opting anyone who requires `celluloid` in their app probably isn't a good idea.

I would suggest removing the `at_exit` handler and having people who want the shutdown behavior explicitly call `Celluloid.shutdown`

/cc @dhh

**Comment by dhh** [comment]
That makes a lot of sense to me. Far better for us to just turn on the at_exit handler for dedicated celluloid processes. Then we wouldn't have it on for the default in-app mounting in development.

**Comment by ioquatix** [comment]
Yes, please remove it. It's causing problems with RubyDNS:

```
/Users/samuel/.rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:407:in `sleep': Interrupt
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:407:in `sleep'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:167:in `block in register_shutdown'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/process-daemon-1.0.1/lib/process/daemon/controller.rb:67:in `fork'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/process-daemon-1.0.1/lib/process/daemon/controller.rb:67:in `spawn'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/process-daemon-1.0.1/lib/process/daemon/controller.rb:113:in `start'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/process-daemon-1.0.1/lib/process/daemon.rb:185:in `start'
	from /Users/samuel/Documents/Programming/Internet/rubydns/spec/rubydns/daemon_spec.rb:70:in `block (2 levels) in <top (required)>'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:357:in `instance_exec'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:357:in `run'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:520:in `each'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/hooks.rb:473:in `run'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:494:in `block in run_before_context_hooks'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:493:in `run_before_context_hooks'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:542:in `run'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (3 levels) in run_specs'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `map'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:119:in `block (2 levels) in run_specs'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1680:in `with_suite_hooks'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:118:in `block in run_specs'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/reporter.rb:77:in `report'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:117:in `run_specs'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:93:in `run'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/samuel/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Celluloid should become a library, using it as a framework should be a specific, explicit step, e.g.

```ruby
require 'celluloid'
Celluloid.boot # Or something which indicates that this is a top level Celluloid managed process?
```

**Comment by tarcieri** [comment]
For what it's worth, that's how it used to work:

`require 'celluloid'` would boot it in library mode

`require 'celluloid/autostart'` would boot it in "framework mode", starting default services and installing the `at_exit` handler.

**Comment by ioquatix** [comment]
Why was it changed?

**Comment by tarcieri** [comment]
Not sure. @digitalextremist ?

**Comment by digitalextremist** [comment]
This changed during the time between 0.15 and 0.17 but I will mop this up. About to do a pre-GSoC pass.

**Comment by ioquatix** [comment]
Have we made any progress on this issue?

**Comment by ioquatix** [comment]
Guys can you please review the PR, we need to get this out ASAP IMHO. IT's breaking shit.

**Comment by ioquatix** [comment]
@digitalextremist Do you care to chime in here w.r.t. what you think is the best way forward. Thanks so much.
