### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by balasankarc** [celluloid/celluloid#707]
I am helping maintaining the ruby-celluloid package in Debian. When building, the latest version gives this test failure

```
/home/balasankarc/packaging/trying/celluloid/ruby-celluloid/spec/celluloid/actor/system_spec.rb:1:in `<top (required)>': uninitialized constant Celluloid (NameError)
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1361:in `load'
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1361:in `block in load_spec_files'
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1359:in `each'
    from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1359:in `load_spec_files'
    from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:106:in `setup'
    from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:92:in `run'
    from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:78:in `run'
    from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:45:in `invoke'
    from /usr/bin/rspec:4:in `<main>'
/usr/bin/ruby2.2 /usr/bin/rspec --pattern ./spec/\*\*/\*_spec.rb failed
```

I tried adding `require 'celluloid'` statement in `spec/celluloid/actor/system_spec.rb` file, but it gave Pathname error for almost all the tests.

Can you help us solve this?

**Comment by ioquatix** [comment]
That's odd, can you give me some more details about the context in which you are running RSpec?

**Comment by digitalextremist** [comment]
@balasankarc sounds like the paths in the environment are incorrect, and/or there's no load path set?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
