### ISSUE TITLE
Crashing: TypeError: exception class/object expected

### ISSUE THREAD

**Issue by tmornini** [celluloid/celluloid#730]
Hey all!

Just saw a very interesting exception and through you'd like to take a look.

I'll debug this further on my side and update this ticket when I know the root cause.

gem versions:

```
    celluloid (0.17.3)
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
    celluloid-essentials (0.20.5)
    celluloid-extras (0.20.5)
    celluloid-fsm (0.20.5)
    celluloid-pool (0.20.5)
    celluloid-supervision (0.20.6)
```

backtrace:

```
E, [2016-08-10T17:06:51.126656 #10807] ERROR -- : Actor crashed!
TypeError: exception class/object expected
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75:in `fail'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:75:in `suspend'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/block.rb:18:in `block in to_proc'
  /Users/tmornini/subledger/trading-engine/subledger/io.rb:17:in `block in each_line'
  /Users/tmornini/subledger/trading-engine/subledger/io.rb:14:in `each'
  /Users/tmornini/subledger/trading-engine/subledger/io.rb:14:in `each_with_index'
  /Users/tmornini/subledger/trading-engine/subledger/io.rb:14:in `each_line'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
  /Users/tmornini/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by tmornini** [comment]
Hey all.

I fixed this issue in my code base by making a class not async.

The method in question read from STDIN and yielded the results. I suspect it was the yield that was an issue.

In any case, that exception thrown was not in any way indicative the problem, so perhaps some work needs to be done on that?

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
