### ISSUE TITLE
Explicit return in block passed to Actor leaves task running

### ISSUE THREAD

**Issue by O1O1O1O** [celluloid/celluloid#750]
If I pass a block that contains an explicit `return` to an Actor method and `call` the block from the actor it will leave a task running.  

```
class Worker
  include Celluloid

  def work(&block)
    block.call
  end
end

def test
  Worker.new.work { return }
end
```
```
> test
=> nil
> Celluloid.dump
# omitted other utility actor traces
Celluloid::Actor 0x3fd563ceccdc
Celluloid::Cell 0x3fd563cecef8: Worker
State: Running (executing tasks)
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `sleep'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `wait'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:63:in `block in check'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:15:in `block in for'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `loop'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/timers-4.1.2/lib/timers/wait.rb:14:in `for'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:58:in `check'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:155:in `block in run'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/timers-4.1.2/lib/timers/group.rb:68:in `wait'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:152:in `run'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
	/Users/Waddington/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'


	Tasks:
	  1) Celluloid::Task::Fibered[call]: invokeblock
	      {:dangerous_suspend=>false, :method_name=>:work}
		Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.


=> []
```

When using an actor pool it sees the actor as still busy and so requests to get an actor from the pool will eventually block.

While `return` is probably a bad thing to do in a block passed to an actor I think it should at least be spelled out as "A Bad Thing" :tm: in the Wiki page [Blocks](https://github.com/celluloid/celluloid/wiki/Blocks) in case someone accidentally does it.

I don't know the Celluloid internals but I'm wondering if it would be possible for the `dispatch` method to actually catch the `LocalJumpError` caused by the `return`. Then it could do something like extract the return value and pretend like the block ended normally.  

Something like changing https://github.com/celluloid/celluloid/blob/master/lib/celluloid/call/block.rb#L16-L19 to:
```
def dispatch
  response = begin
    @block_proxy.block.call(*@arguments)
  rescue LocalJumpError => e
     # Log warning? Or propagate the error safely
     e.exit_value
  end
  @sender << Internals::Response::Block.new(self, response)
end
```
That's a bit of a lie and not what the normal non-Celluloid behavior would be so alternatively if we are to say "explicit return from blocks based to actors is not permitted" then it could treat it like an exception, clean up properly and log an error?  

Or finally it could clean up the task fiber properly and then propagate the LocalJumpError to the Actor method to maintain Actor/non-Actor execution behavior parity.

**Comment by tarcieri** [comment]
If you'd like to send a PR for that change we can discuss it there

**Comment by O1O1O1O** [comment]
Okay, I'll work on it and submit the PR - I just wanted to see if you thought I was completely off-base with that suggestion.

**Comment by tarcieri** [comment]
Looks good to me 👍

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
