### ISSUE TITLE
Consecutive Celluloid.boot / Celluloid.shutdown calls throw Celluloid::Supervision::Configuration::Error::InvalidSupervisor

### ISSUE THREAD

**Issue by dlau** [celluloid/celluloid#758]
Hi,

In specs, I am calling `Celluloid.boot` and `Celluloid.shutdown` before and after each block evaluation, per recommended usage in the wiki.

Gemfile:
```rb
# frozen_string_literal: true
source "https://rubygems.org"

gem "celluloid", "0.18.0.pre"
gem "rspec"

```

Here is a stripped down test file:

```rb
require 'rspec'
require 'celluloid/current'

RSpec.describe 'foo' do
  before(:each) do
    Celluloid.boot
  end

  after(:each) do
    Celluloid.shutdown
  end

  it '1' do
    expect(1).to eq(1)
  end
  it '2' do
    expect(2).to eq(2)
  end
end
```

When run, the output looks like this:
```sh
~/dev/celluloid-test rake                                                                                                                                    
Failures:

  1) foo 2
     Failure/Error: Celluloid.boot

     Celluloid::Supervision::Configuration::Error::InvalidSupervisor:
       Celluloid::Supervision::Configuration::Error::InvalidSupervisor
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/configuration.rb:58:in `provider'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/configuration.rb:52:in `provider'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/configuration.rb:65:in `block in deploy'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/configuration.rb:64:in `each'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-supervision-0.20.6/lib/celluloid/supervision/configuration.rb:64:in `deploy'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-0.18.0.pre/lib/celluloid/actor/system.rb:61:in `block in start'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-0.18.0.pre/lib/celluloid/actor/system.rb:70:in `within'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-0.18.0.pre/lib/celluloid/actor/system.rb:59:in `start'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-0.18.0.pre/lib/celluloid.rb:155:in `start'
     # /Users/daryllau/.rvm/gems/ruby-2.3.1/gems/celluloid-0.18.0.pre/lib/celluloid.rb:147:in `boot'
     # ./spec/test_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.00671 seconds (files took 0.1773 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/test_spec.rb:21 # foo 2
```

This is causing most complex test cases to fail in a more complex test case in our fork of [celluloid-eventsource](https://github.com/launchdarkly/celluloid-eventsource/tree/0.9.0-release)

**Comment by florin555** [comment]
A quick and dirty fix that I found to work is:

```
Celluloid.shutdown
Celluloid.instance_variable_set(:@actor_system, nil)
Celluloid.boot
```

**Comment by tarcieri** [comment]
Seems like this is a bug in `Celluloid.shutdown` then and it should be terminating and clearing `@actor_system`
