### ISSUE TITLE
Segmentation fault in Ruby 2.5.3 

### ISSUE THREAD

**Issue by sivagollapalli** [celluloid/celluloid#815]
```
require 'celluloid'
require 'celluloid/autostart'
require "celluloid/pool" 

class CelluloidDemo 
  include Celluloid

  def greet 
    puts "Hello from celluloid..."
  end
end

pool = CelluloidDemo.pool(size: 5) 

10.times { pool.greet }
```

```
/Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task.rb:163: [BUG] Segmentation fault at 0x000070000c6f1560
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin19]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0004 p:0009 s:0016 e:000014 METHOD /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task.rb:163
c:0003 p:0072 s:0010 e:000008 BLOCK  /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task.rb:48
c:0002 p:0057 s:0006 e:000005 BLOCK  /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task/fibered.rb:14 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task/fibered.rb:14:in `block in create'
/Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task.rb:48:in `block in initialize'
/Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task.rb:163:in `name_current_thread'

-- Machine register context ------------------------------------------------
 rax: 0x00007fc9fa606e70 rbx: 0x00007fc9ffd00000 rcx: 0x000000000000008b
 rdx: 0xda51c292815ee904 rdi: 0x00007fc9fc7342e8 rsi: 0x00007fc9fa8a55b8
 rbp: 0x000070000c5ee530 rsp: 0x000070000c5ee500  r8: 0x00007fc9fa608300
  r9: 0xcccccccccccccccd r10: 0x000000000005607a r11: 0x00007fc9fb12ef68
 r12: 0x000070000c6f1560 r13: 0x0666666666666666 r14: 0x00007fc9fa607470
 r15: 0x0000000000000145 rip: 0x000000010bc65290 rfl: 0x0000000000010202

-- C level backtrace information -------------------------------------------
0   libruby.2.5.dylib                   0x000000010bdcc048 rb_vm_bugreport + 136
1   libruby.2.5.dylib                   0x000000010bc4b556 rb_bug_context + 470
2   libruby.2.5.dylib                   0x000000010bd3db11 sigsegv + 81
3   libsystem_platform.dylib            0x00007fff69f185fd _sigtramp + 29
4   libruby.2.5.dylib                   0x000000010bc65290 rb_gc_mark_machine_stack + 112
5   libruby.2.5.dylib                   0x000000010bdbaa39 rb_execution_context_mark + 137
6   libruby.2.5.dylib                   0x000000010bc32bfb cont_mark + 27
7   libruby.2.5.dylib                   0x000000010bc702ab gc_mark_stacked_objects_incremental + 171
8   libruby.2.5.dylib                   0x000000010bc6da83 newobj_slowpath + 675
9   libruby.2.5.dylib                   0x000000010bc6d7b4 newobj_slowpath_wb_protected + 20
10  libruby.2.5.dylib                   0x000000010bd547ea rb_str_resurrect + 58
11  libruby.2.5.dylib                   0x000000010bdae68c vm_exec_core + 38588
12  libruby.2.5.dylib                   0x000000010bdb9768 vm_exec + 184
13  libruby.2.5.dylib                   0x000000010bdb81cd vm_invoke_proc + 285
14  libruby.2.5.dylib                   0x000000010bc31b97 rb_fiber_start + 455
15  libruby.2.5.dylib                   0x000000010bd7eb87 thread_start_func_2 + 1943
16  libruby.2.5.dylib                   0x000000010bd7e3c8 thread_start_func_1 + 184
17  libsystem_pthread.dylib             0x00007fff69f24109 _pthread_start + 148

-- Other runtime information -----------------------------------------------

* Loaded script: celluloid_demo.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/x86_64-darwin19/enc/encdb.bundle
    5 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/x86_64-darwin19/enc/trans/transdb.bundle
    6 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/x86_64-darwin19/rbconfig.rb
    7 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/compatibility.rb
    8 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/defaults.rb
    9 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/deprecate.rb
   10 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/errors.rb
   11 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/path_support.rb
   12 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/version.rb
   13 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/requirement.rb
   14 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/platform.rb
   15 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/basic_specification.rb
   16 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/stub_specification.rb
   17 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/delegate.rb
   18 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/rfc2396_parser.rb
   19 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/rfc3986_parser.rb
   20 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/common.rb
   21 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/generic.rb
   22 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/ftp.rb
   23 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/http.rb
   24 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/https.rb
   25 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/ldap.rb
   26 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/ldaps.rb
   27 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/mailto.rb
   28 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri.rb
   29 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/specification_policy.rb
   30 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/util/list.rb
   31 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/x86_64-darwin19/stringio.bundle
   32 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb
   33 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/exceptions.rb
   34 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/util.rb
   35 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/bundler_version_finder.rb
   36 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb
   37 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_gem.rb
   38 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/monitor.rb
   39 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb
   40 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb
   41 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb
   42 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/version.rb
   43 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/core_ext/name_error.rb
   44 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/levenshtein.rb
   45 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/jaro_winkler.rb
   46 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checker.rb
   47 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   48 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   49 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   50 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   51 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/key_error_checker.rb
   52 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/null_checker.rb
   53 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/formatters/plain_formatter.rb
   54 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean.rb
   55 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/English.rb
   56 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/logger.rb
   57 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/set.rb
   58 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/timeout.rb
   59 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/version.rb
   60 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/exceptions.rb
   61 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/call/sync.rb
   62 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/call/async.rb
   63 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/call/block.rb
   64 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/calls.rb
   65 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/condition.rb
   66 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/thread.rb
   67 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/core_ext.rb
   68 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/system_events.rb
   69 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxy/abstract.rb
   70 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxy/sync.rb
   71 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxy/cell.rb
   72 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxy/actor.rb
   73 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxy/async.rb
   74 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxy/future.rb
   75 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxy/block.rb
   76 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/proxies.rb
   77 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/mailbox.rb
   78 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/mailbox/evented.rb
   79 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/group.rb
   80 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/group/spawner.rb
   81 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/group/pool.rb
   82 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task.rb
   83 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task/fibered.rb
   84 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/task/threaded.rb
   85 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers/version.rb
   86 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable/impl.rb
   87 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb
   88 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers/interval.rb
   89 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers/timer.rb
   90 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers/priority_heap.rb
   91 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers/events.rb
   92 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers/group.rb
   93 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers/wait.rb
   94 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/timers-4.3.3/lib/timers.rb
   95 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/actor.rb
   96 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/cell.rb
   97 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/future.rb
   98 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/call_chain.rb
   99 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/cpu_counter.rb
  100 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/handlers.rb
  101 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/links.rb
  102 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/logger.rb
  103 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/method.rb
  104 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/properties.rb
  105 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/receivers.rb
  106 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/registry.rb
  107 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/responses.rb
  108 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/signals.rb
  109 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/stack/states.rb
  110 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/stack/dump.rb
  111 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/stack/summary.rb
  112 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/stack.rb
  113 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/task_set.rb
  114 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/thread_handle.rb
  115 /Users/sivagollapalli/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/securerandom.rb
  116 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/internals/uuid.rb
  117 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/notifications.rb
  118 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/constants.rb
  119 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/supervise.rb
  120 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/container.rb
  121 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/container/instance.rb
  122 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/container/behavior.rb
  123 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/container/injections.rb
  124 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/container/behavior/tree.rb
  125 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/validation.rb
  126 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/configuration.rb
  127 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/configuration/instance.rb
  128 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/service.rb
  129 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision.rb
  130 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/logging/log_event.rb
  131 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/logging/incident.rb
  132 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/logging/ring_buffer.rb
  133 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/logging/incident_logger.rb
  134 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/logging/incident_reporter.rb
  135 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/logging.rb
  136 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/actor/system.rb
  137 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid.rb
  138 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/autostart.rb
  139 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/container/pool.rb
  140 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/supervision/container/behavior/pool.rb
  141 /Users/sivagollapalli/.rvm/gems/ruby-2.5.3/gems/celluloid-0.18.0/lib/celluloid/pool.rb
```

But in Ruby 2.7.0 it works fine

**Comment by bogdanRada** [comment]
I had same problem so i did this for celluloid 0.18

 ​  ​require​ ​'celluloid' 
 ​  ​require​ ​'celluloid/pool' 
 ​  ​require​ ​'celluloid/fsm' 
 ​  ​require​ ​'celluloid/supervision'

You might not need all of the above. 
 
And i required celluiloid/autostart at the end. Well actually i am booting up differently using a static method on a class. 

```ruby
 
 ​      ​def​ ​boot_up 
 ​        ​celluloid_running​ ​=​ ​begin 
 ​          ​Celluloid​.​running? 
 ​        ​rescue​ ​StandardError 
 ​          ​false 
 ​        ​end 
 ​        ​Celluloid​.​boot​ ​unless​ ​celluloid_running 
 ​      ​end
    ```

This is just so i can avoid booting up twice if i require this file multiple times.

Hope this helps.
